apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongodb-ops-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  Username: "PLACEHOLDER"
  Password: "PLACEHOLDER"
  FirstName: "PLACEHOLDER"
  LastName: "PLACEHOLDER"
