apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-credentials
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  aws_access_key_id: "PLACEHOLDER"
  aws_secret_access_key: "PLACEHOLDER"
