apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/ops-manager
  - ../../base/mongodb-data

patches:
  - path: external-dns-patch.yaml
    target:
      kind: Deployment
      name: external-dns
  - path: ops-manager-connection-patch.yaml
    target:
      kind: ConfigMap
      name: ops-manager-connection
